PriceMonitorProj/PriceMonitor/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from users import views as user_views
from users.forms import CustomLoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',
         views.LoginView.as_view(
             template_name='users/login.html',
             authentication_form=CustomLoginForm),
         name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('password-reset/',
         views.PasswordResetView.as_view(
             template_name='users/password_reset.html',
             email_template_name='users/password_reset_email.html',
             subject_template_name='users/password_reset_subject.txt'
         ),
         name='password_reset'),
    path('password-reset/done',
         views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>',
         views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('', include('tracked_prices.urls'))
]

PriceMonitorProj/tracked_prices/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('error/', views.scrape_error, name='scrape_error'),
    path('pufcia/', views.pufcia, name='pufcia'),
    path('shops/', views.sklepy, name='shops'),
    path('prices/', views.tracked_prices_list, name='tracked_prices_list'),
    path('price/new/', views.price_new, name='price_new'),
    path('price/<int:pk>/edit/', views.price_edit, name='price_edit'),
    path('price/<int:pk>/remove/', views.PriceDeleteView.as_view(), name='price_remove'),
]

PriceMonitorProj/tracked_prices/models.py
import re

from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone


class TrackedPrice(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=500)
    url = models.URLField(max_length=500)

    current = models.FloatField()
    currency = models.CharField(max_length=5)

    CHOICES = (
        ('A', 'gdy cena spadnie'),
        ('B', 'gdy cena spadnie o x procent'),
        ('C', 'gdy cena osiągnie pożądaną wartość')
    )
    when_inform = models.CharField(max_length=1, choices=CHOICES, default='A')
    desired = models.FloatField(default=1)
    percent_drop = models.PositiveSmallIntegerField(default=5, validators=[
        MinValueValidator(1),
        MaxValueValidator(100)
    ])

    last_checked_date = models.DateTimeField(default=timezone.now)

    def track(self):
        self.last_checked_date = timezone.now()
        self.save()

    def __str__(self):
        return self.name


class Shop(models.Model):
    url = models.URLField(max_length=100)
    name = models.CharField(max_length=500)

    def __str__(self):
        return re.search(r'https?://(www\.)?(.*?)/', self.url).group(2)

PriceMonitorProj/tracked_prices/forms.py
from django import forms

from .models import TrackedPrice


class NewPriceForm(forms.ModelForm):
    class Meta:
        model = TrackedPrice
        fields = ('url',
                  'when_inform',
                  'percent_drop',
                  'desired')
        widgets = {
            'url': forms.URLInput(attrs={'placeholder': 'https://'})
        }
        labels = {
            'url': 'Adres produktu',
            'when_inform': 'Wyślij powiadomienie',
            'desired': '',
            'percent_drop': ''
        }


class EditPriceForm(forms.ModelForm):
    class Meta:
        model = TrackedPrice
        fields = ('name',
                  'when_inform',
                  'percent_drop',
                  'desired')
        labels = {
            'name': 'Nazwa produktu',
            'when_inform': 'Wyślij powiadomienie',
            'desired': '',
            'percent_drop': ''
        }

PriceMonitorProj/tracked_prices/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.views.generic import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.conf import settings
from django.core.mail import send_mail
from django_tables2 import RequestConfig

from scrape_prices.scrape import get_name_price_currency, price_drop_inform
from .models import TrackedPrice, Shop
from .forms import NewPriceForm, EditPriceForm
from .tables import PriceTable


def home(request):
    """Renders home page."""
    return render(request, 'tracked_prices/home.html')


def pufcia(request):
    """Test method for testing scrape.price_drop_inform"""
    price_drop_inform()
    return render(request, 'tracked_prices/pufcia.html')


def sklepy(request):
    """Renders the page with all shops list."""
    shops = Shop.objects.all().order_by('name')
    for shop in shops:
        shop.name = shop.__str__()
    return render(request, 'tracked_prices/shops.html', {'shops': shops})


def scrape_error(request, err_message):
    """Renders error page when price can't be found in provided url

    :param err_message: an error message to be shown to user
    """
    return render(request, 'tracked_prices/error_page.html', {'error': err_message})


@login_required
def tracked_prices_list(request):
    """Renders the site with table that shows all prices tracked by the user."""
    user = User.objects.get(username=request.user.username)
    prices = TrackedPrice.objects.filter(user=user).order_by('-last_checked_date')
    table = PriceTable(prices)
    RequestConfig(request, paginate={'per_page': 10}).configure(table)
    return render(request, 'tracked_prices/tracked_prices_list.html', {'table': table})


@login_required
def price_new(request):
    """Renders the form for tracking new prices."""
    if request.method == "POST":
        form = NewPriceForm(request.POST)
        if form.is_valid():
            price = form.save(commit=False)

            try:
                price.name, price.current, price.currency = get_name_price_currency(
                    price.url)
            except ConnectionError:
                return scrape_error(request, 'Nie udało się połączyć ze stroną')
            except KeyError:
                send_mail('Nowy sklep do dodania',
                          f'Użytkownik nie znalazł ceny pod adresem {price.url}',
                          settings.EMAIL_HOST_USER,
                          recipient_list=(settings.EMAIL_HOST_USER,), )
                return scrape_error(request, 'Tego sklepu nie obsługujemy')
            except IndexError:
                return scrape_error(request, 'Nie mogę znaleźć ceny na tej stronie')

            price.user = request.user
            price.last_checked_date = timezone.now()
            price.save()
            return redirect('tracked_prices_list')
    else:
        form = NewPriceForm()

    return render(request, 'tracked_prices/price_new.html', {'form': form})


@login_required
def price_edit(request, pk):
    """Renders price edit form view.

    :param pk: primary key of a tracked price
    """
    price = get_object_or_404(TrackedPrice, pk=pk)
    if request.method == "POST":
        form = EditPriceForm(request.POST, instance=price)
        if form.is_valid():
            price = form.save(commit=False)
            price.save()
            return redirect('tracked_prices_list')
    else:
        form = EditPriceForm(instance=price)

    return render(request, 'tracked_prices/price_edit.html', {'form': form})


class PriceDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Renders the price delete view."""
    model = TrackedPrice

    def test_func(self):
        price = self.get_object()
        if self.request.user == price.user:
            return True
        return False

    def get_success_url(self):
        return '/prices/'

PriceMonitorProj/tracked_prices/templates/tracked_prices/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Cebula Hunter</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'tracked_prices.css' %}">
    <link href="https://fonts.googleapis.com/css?family=News+Cycle&display=swap&subset=latin-ext" rel="stylesheet">

</head>
<body onload="add_hide()"  style="padding-top: 90px;
                                  padding-bottom: 40px;
                                  background-image: url({% static 'pinstripe.png' %});
                                  font-family: 'News Cycle', sans-serif;">
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top text-nowrap"
             style="font-size: 18px;
             background-color: #608850;">
            <a class="navbar-brand" href="/"
               style="font-size: 26px;
                      color: SpringGreen;">
                <img src="{% static 'logo.png' %}" height="40"> Cebula Hunter
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shops' %}">Obsługiwane sklepy</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tracked_prices_list' %}">Śledzone ceny</a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <li class="text-light">
                        <a href="{% url 'price_new' %}" class="nav-link">
                            <i class="fas fa-plus-square text-light px-1"></i>
                            Nowa cena
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'profile' %}" class="nav-link">
                            <i class="fas fa-user-circle text-light px-1"></i>
                            Profil
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}" class="nav-link">
                            <i class="fas fa-lock text-light px-1"></i>
                            Wyloguj
                        </a>
                    </li>
                    {% else %}
                    <li>
                        <a class="nav-link" href="{% url 'register' %}">
                            <i class="fas fa-key text-light px-1"></i>
                            Zarejestruj się
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'login' %}">
                            <i class="fas fa-unlock-alt text-light px-1"></i>
                            Zaloguj
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>


    <main role="main" class="flex-shrink-0">
        <div class="container" style="min-height: calc(82vh);">
                {% if messages %}
                    <div class="row">
                        <div class="col"></div>
                        <div class="col-md-6">
                            {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}">
                                {{ message }}
                            </div>
                            {% endfor %}
                        </div>
                        <div class="col"></div>
                    </div>
                {% endif %}
                {% block content %}{% endblock %}
                {% block js %}{% endblock js %}
        </div>
    </main>


    <footer class="footer mt-auto pt-4 pb-2"
            style="
                   height: 40px;">
      <div class="container text-center">
        <span class="text-muted">&copy; 2019 Marcin Sobala</span>
        <span class="mx-5">
            <span class="text-muted pr-2">Kontakt:</span>
            <a href="https://www.facebook.com/marcin.st.77"
               class="text-light mx-1 nounderline" style="background-color: #3B5998">
                <i class="fab fa-facebook-square pl-1"></i>
            </a>
            <a href="https://www.linkedin.com/in/marcin-sobala-09258118a/"
               class="text-light mx-1 nounderline" style="background-color: #0077B5">
                <i class="fab fa-linkedin pl-1"></i>
            </a>
            <a href="mailto:marcin.sobala09@gmail.com"
               class="text-light mx-1 nounderline" style="background-color: red">
                <i class="far fa-envelope px-1"></i>
            </a>

        </span>
      </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

PriceMonitorProj/tracked_prices/templates/tracked_prices/error_page.html
{% extends 'tracked_prices/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

    <div class="row">
        <div class="col"></div>
        <div class="col-md-6 text-center">
            <img src ="{% static 'error.png' %}" height="300" width="400">
            <h3>Coś poszło nie tak :/</h3>
            <p>{{error}}</p>
        </div>
        <div class="col"></div>
    </div>

{% endblock %}

PriceMonitorProj/tracked_prices/templates/tracked_prices/home.html
{% extends 'tracked_prices/base.html' %}
{% load static %}

{% block content %}

    <div class="row">
        <div class="col"></div>
        <div class="col-md-9 text-center">
            <h3 class="text-dark my-4">Jak oszczędzać z cebulą?</h3>
            <div>
                <img src="{% static 'main.png' %}" height="300" width="300" class="d-inline-block">
                <span class="d-inline-block align-middle">
                    <ol class="text-left">
                        {% if not user.is_authenticated %}
                        <li class="mb-2">
                            <a href="{% url 'login' %}">Zaloguj się</a>
                            , a jeśli jeszcze nie masz konta -
                            <a href ="{% url 'register' %}">załóż je!</a>
                        </li>
                        {% endif %}
                        <li class="mb-2">Znajdź w sieci upragniony przedmiot.</li>
                        <li class="mb-2">
                            {% if user.is_authenticated %}
                                <a href="{% url 'price_new' %}">Podaj</a>
                            {% else %}
                                Podaj
                            {% endif %}
                                 stronie link do zakupu.</li>
                        <li class="mb-2">
                            Śpij spokojnie i pozwól Cebuli czuwać. <br>
                            Gdy cena spadnie, otrzymasz maila!
                        </li>
                        <li class="mb-2"><b>Profit!</b></li>
                    </ol>
                </span>

            </div>

            <br>
            <a class="btn btn-primary" href="{% url 'pufcia' %}">Pufcia is awesome!</a>
        </div>
        <div class="col"></div>
    </div>

{% endblock %}

PriceMonitorProj/tracked_prices/templates/tracked_prices/price_edit.html
{% extends 'tracked_prices/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="row">
        <div class="col"></div>
        <div class="col-xs-6">
            <form method="post" class="post-form">
                {% csrf_token %}
                <fieldset class="form-group">
                    {{ form|crispy }}
                </fieldset>
                <script>function add_hide()
                {
                    Hide();
                    $("#id_when_inform")[0].addEventListener("change", Hide);
                }
                </script>
                <button type="submit" class="save btn btn-primary">Zapisz zmiany</button>
            </form>
        </div>
        <div class="col"></div>
    </div>

{% endblock %}

{% block js %}

    <script>function Hide()
    {
        if($('#id_when_inform')[0].value == "A")
        {
            $('#div_id_percent_drop')[0].style.display = 'none';
            $('#div_id_desired')[0].style.display = 'none';
        }
        else if($('#id_when_inform')[0].value == "B")
        {
            $('#div_id_percent_drop')[0].style.display = '';
            $('#div_id_desired')[0].style.display = 'none'
        }
        else
        {
            $('#div_id_percent_drop')[0].style.display = 'none';
            $('#div_id_desired')[0].style.display = ''
        }
    }
    </script>

{% endblock js %}

PriceMonitorProj/tracked_prices/templates/tracked_prices/price_new.html
{% extends 'tracked_prices/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="row">
        <div class="col"></div>
        <div class="col-xs-6">
            <form method="post" class="post-form">
                {% csrf_token %}
                <fieldset class="form-group">
                    {{ form|crispy }}
                </fieldset>

                <script>function add_hide()
                {
                    Hide();
                    $("#id_when_inform")[0].addEventListener("change", Hide);
                }
                </script>
                <button type="submit" class="save btn btn-primary">Śledź cenę</button>
            </form>
        </div>
        <div class="col"></div>
    </div>

{% endblock %}

{% block js %}

    <script>function Hide()
    {
        if($('#id_when_inform')[0].value == "A")
        {
            $('#div_id_percent_drop')[0].style.display = 'none';
            $('#div_id_desired')[0].style.display = 'none';
        }
        else if($('#id_when_inform')[0].value == "B")
        {
            $('#div_id_percent_drop')[0].style.display = '';
            $('#div_id_desired')[0].style.display = 'none'
        }
        else
        {
            $('#div_id_percent_drop')[0].style.display = 'none';
            $('#div_id_desired')[0].style.display = ''
        }
    }
    </script>

{% endblock js %}

PriceMonitorProj/tracked_prices/templates/tracked_prices/pufcia.html
{% extends 'tracked_prices/base.html' %}

{% block content %}
    <div class="col text-center">
        <a class="btn btn-danger" href="{% url 'home' %}">  <3  :****</a>
    </div>
    <br>
    <p class="text-center">Yes, she is!</p>
    {% for price in prices %}
        <p>{{price}}</p>
    {% endfor %}

{% endblock %}

PriceMonitorProj/tracked_prices/templates/tracked_prices/shops.html
{% extends 'tracked_prices/base.html' %}

{% block content %}
    <div class="row">
        <div class="col"></div>
        <div class="col-md-9 text-center">
            <h3 class="text-dark my-4">Najlepiej oceniane sklepy w polskim internecie</h3>
            {% for shop in shops %}
                <a href="{{ shop.url }}" class="shop">
                    {{ shop.name }}
                </a>
            {% endfor %}
        </div>
        <div class="col"></div>
    </div>

{% endblock %}

PriceMonitorProj/tracked_prices/templates/tracked_prices/table.html
{% load django_tables2 %}
{% load i18n %}
{% block table-wrapper %}
<div class="table-container">
    {% block table %}
        <table {% render_attrs table.attrs class="table" %}>
            {% block table.thead %}
            {% if table.show_header %}
                <thead class="thead-default" {{ table.attrs.thead.as_html }}>
                <tr>
                {% for column in table.columns %}
                    <th {{ column.attrs.th.as_html }}>
                        {% if column.orderable %}
                            <a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">
                              {{ column.header }}
                            </a>
                        {% else %}
                            {{ column.header }}
                        {% endif %}
                    </th>
                {% endfor %}
                </tr>
                </thead>
            {% endif %}
            {% endblock table.thead %}
            {% block table.tbody %}
                <tbody {{ table.attrs.tbody.as_html }}>
                {% for row in table.paginated_rows %}
                    {% block table.tbody.row %}
                    <tr scope="row" {{ row.attrs.as_html }}>
                        {% for column, cell in row.items %}
                            <td {{ column.attrs.td.as_html }}>{% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}</td>
                        {% endfor %}
                    </tr>
                    {% endblock table.tbody.row %}
                {% empty %}
                    {% if table.empty_text %}
                    {% block table.tbody.empty_text %}
                        <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
                    {% endblock table.tbody.empty_text %}
                    {% endif %}
                {% endfor %}
                </tbody>
            {% endblock table.tbody %}
            {% block table.tfoot %}
            {% if table.has_footer %}
            <tfoot {{ table.attrs.tfoot.as_html }}>
                <tr>
                {% for column in table.columns %}
                    <td {{ column.attrs.tf.as_html }}>{{ column.footer }}</td>
                {% endfor %}
                </tr>
            </tfoot>
            {% endif %}
            {% endblock table.tfoot %}
        </table>
    {% endblock table %}

    {% block pagination %}
        {% if table.page and table.paginator.num_pages > 1 %}
        <nav aria-label="Table navigation">
            <ul class="pagination justify-content-center">
            {% if table.page.has_previous %}
                {% block pagination.previous %}
                <li class="previous page-item">
                    <a href="{% querystring table.prefixed_page_field=table.page.previous_page_number %}" class="page-link bg-light border-dark">
                        <span aria-hidden="true">&laquo;</span>
                        {% trans 'previous' %}
                    </a>
                </li>
                {% endblock pagination.previous %}
            {% endif %}
            {% if table.page.has_previous or table.page.has_next %}
            {% block pagination.range %}
            {% for p in table.page|table_page_range:table.paginator %}
                <li class="page-item{% if table.page.number == p %} active{% endif %}">
                    <a class="page-link border-dark {% if table.page.number == p %} bg-primary {% else %} bg-light {% endif %} "
                       {% if p != '...' %}href="{% querystring table.prefixed_page_field=p %}"{% endif %}>
                        {{ p }}
                    </a>
                </li>
            {% endfor %}
            {% endblock pagination.range %}
            {% endif %}
            {% if table.page.has_next %}
                {% block pagination.next %}
                <li class="next page-item">
                    <a href="{% querystring table.prefixed_page_field=table.page.next_page_number %}" class="page-link bg-light border-dark">
                        {% trans 'next' %}
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endblock pagination.next %}
            {% endif %}
            </ul>
        </nav>
        {% endif %}
    {% endblock pagination %}
</div>
{% endblock table-wrapper %}

PriceMonitorProj/tracked_prices/templates/tracked_prices/tracked_prices_list.html
{% extends 'tracked_prices/base.html' %}

{% block content %}

{% load render_table from django_tables2 %}

{% render_table table %}

{% endblock %}

PriceMonitorProj/tracked_prices/templates/tracked_prices/trackedprice_confirm_delete.html
{% extends "tracked_prices/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-md-6">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <p class="mt-4">Czy na pewno nie chcesz już śledzić ceny "{{ object.name }}"?</p>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">Tak, na pewno</button>
                <a class="btn btn-secondary" href="{% url 'tracked_prices_list' %}">Anuluj</a>
            </div>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock content %}